const DEMO = [
 ['APU INOP','ВСУ не работает','APU'],
 ['PACK 1 INOP','Пак 1 не работает','Air conditioning'],['PACK 2 INOP','Пак 2 не работает','Air conditioning'],
 ['ENG BLEED 1 INOP','Отбор воздуха от двигателя 1 не работает','Pneumatic'],['ENG BLEED 2 INOP','Отбор воздуха от двигателя 2 не работает','Pneumatic'],
 ['GEN 1 INOP','Генератор 1 не работает','Electrical'],['GEN 2 INOP','Генератор 2 не работает','Electrical'],
 ['WEATHER RADAR INOP','Метеорадар не работает','Navigation'],
 ['LANDING LIGHT L INOP','Левая посадочная фара не работает','Lights'],['LANDING LIGHT R INOP','Правая посадочная фара не работает','Lights'],
 ['REVERSER 1 INOP','Реверс двигателя 1 не работает','Powerplant'],['REVERSER 2 INOP','Реверс двигателя 2 не работает','Powerplant']
].map(([title,description,system],i)=>({id:`demo-${i}`,title,description,system}));
const $=id=>document.getElementById(id);
let catalog={name:'Демонстрационный список · не MEL',items:DEMO},history=[],current=null;
try{const saved=JSON.parse(localStorage.getItem('mel-history')||'[]');if(Array.isArray(saved))history=saved.filter(x=>x&&typeof x.registration==='string'&&typeof x.date==='string'&&Array.isArray(x.items)&&x.items.every(y=>y&&typeof y.title==='string'&&typeof y.description==='string'&&typeof y.system==='string')).slice(0,20);}catch{}
function el(tag,text,cls){const node=document.createElement(tag);node.textContent=text;if(cls)node.className=cls;return node;}
function save(){try{localStorage.setItem('mel-history',JSON.stringify(history));}catch{$('message').textContent='Браузер не разрешил сохранить историю.';}}
function updateCatalog(){ $('source').textContent=`${catalog.name} · ${catalog.items.length} дефектов`; $('system').replaceChildren(new Option('Все системы','all'));[...new Set(catalog.items.map(x=>x.system))].sort().forEach(x=>$('system').add(new Option(x,x)));}
function randomInt(max){const range=4294967296,limit=range-range%max;let n;do{n=crypto.getRandomValues(new Uint32Array(1))[0];}while(n>=limit);return n%max;}
function choose(items,count){const pool=[...items];for(let i=pool.length-1;i>0;i--){let j=randomInt(i+1);[pool[i],pool[j]]=[pool[j],pool[i]];}return pool.slice(0,count);}
function render(s){current=s;$('aircraft').textContent=`A320 · ${s.registration}`;$('status').textContent=s.items.length?`${s.items.length} ДЕФЕКТ(А)`:'БЕЗ ДЕФЕКТОВ';$('date').textContent=new Date(s.date).toLocaleString('ru-RU');$('copy').disabled=false;$('result').replaceChildren();if(!s.items.length)$('result').append(el('div','Сценарий: самолёт без сгенерированных дефектов.','empty'));s.items.forEach((x,i)=>{const card=el('div','','defect');card.append(el('span',`${String(i+1).padStart(2,'0')} / ${x.system}`,'tag'),el('h3',x.title),el('p',x.description));if(x.reference)card.append(el('p',`Пункт MEL: ${x.reference}`));if(x.notes)card.append(el('p',x.notes));card.append(el('p',x.reference?'Сверьте условия с исходным MEL.':'Пункт MEL и условия допуска не заданы.','small'));$('result').append(card);});}
function renderHistory(){ $('history').replaceChildren();if(!history.length)$('history').append(el('p','Сгенерированные сценарии появятся здесь.'));history.forEach(s=>{const b=el('button',`${s.registration} · ${s.items.map(x=>x.title).join(' / ')||'Без дефектов'}`,'history-item');b.append(el('small',`${new Date(s.date).toLocaleString('ru-RU')} · ${s.source||'Демонстрационный список'}`));b.onclick=()=>render(s);$('history').append(b);});}
$('generate').onclick=()=>{const pool=catalog.items.filter(x=>$('system').value==='all'||x.system===$('system').value);let count=$('count').value==='random'?1+randomInt(3):Number($('count').value);if($('serviceable').checked&&randomInt(100)<30)count=0;const actual=Math.min(count,pool.length);$('message').textContent=actual<count?`В выбранной системе только ${actual} дефект(а).`:'';const s={registration:$('registration').value.trim().toUpperCase()||'Борт не указан',date:new Date().toISOString(),source:catalog.name,items:choose(pool,actual)};history.unshift(s);history=history.slice(0,20);save();render(s);renderHistory();};
$('copy').onclick=async()=>{if(!current)return;const text=[`A320 / ${current.registration}`,new Date(current.date).toLocaleString('ru-RU'),`Источник: ${current.source}`,...current.items.map(x=>`${x.title} — ${x.description}${x.reference?' / MEL '+x.reference:''}${x.notes?' / '+x.notes:''}`),current.items.length?'Условия допуска и совместимость: проверить по исходному MEL.':'Без сгенерированных дефектов.','Только для авиасимулятора.'].join('\n');try{await navigator.clipboard.writeText(text);$('message').textContent='Запись скопирована.';}catch{$('message').textContent='Копирование недоступно в этом браузере. Выделите запись вручную.';}};
$('clear').onclick=()=>{history=[];save();renderHistory();};
$('reset').onclick=()=>{catalog={name:'Демонстрационный список · не MEL',items:DEMO};updateCatalog();$('message').textContent='Демонстрационный список восстановлен.';};
$('import').onchange=async event=>{const file=event.target.files[0];if(!file)return;try{if(file.size>2000000)throw Error('Максимальный размер — 2 МБ.');const data=JSON.parse(await file.text());if(typeof data.name!=='string'||!data.name.trim()||!Array.isArray(data.items)||!data.items.length||data.items.length>5000)throw Error('Нужны name и непустой массив items (до 5000 записей).');const ids=new Set();for(const item of data.items){for(const key of ['id','title','description','system'])if(typeof item[key]!=='string'||!item[key].trim())throw Error(`У каждой записи должно быть текстовое поле ${key}.`);for(const key of ['reference','notes'])if(item[key]!==undefined&&typeof item[key]!=='string')throw Error(`Поле ${key} должно быть строкой.`);if(ids.has(item.id))throw Error('Идентификаторы id должны быть уникальны.');ids.add(item.id);}catalog=data;updateCatalog();$('message').textContent='Каталог загружен на текущий сеанс.';}catch(error){$('message').textContent=`Каталог не загружен: ${error.message}`;}event.target.value='';};
updateCatalog();renderHistory();
