<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net8.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>

    <IsPackable>false</IsPackable>
    <IsTestProject>true</IsTestProject>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="coverlet.collector" Version="6.0.0" />
    <PackageReference Include="Microsoft.NET.Test.Sdk" Version="17.8.0" />
    <PackageReference Include="xunit" Version="2.5.3" />
    <PackageReference Include="xunit.runner.visualstudio" Version="2.5.3" />
  </ItemGroup>

  <ItemGroup>
    <Using Include="Xunit" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\..\..\production\service\MelGenerator.Core\MelGenerator.Core.csproj" />
  </ItemGroup>

  <ItemGroup>
    <Content Include="..\..\..\production\data\catalog.json" Link="data\catalog.json" CopyToOutputDirectory="PreserveNewest" />
    <Content Include="..\..\..\production\data\rules.json" Link="data\rules.json" CopyToOutputDirectory="PreserveNewest" />
    <Content Include="..\..\research_fenix\efb_mmel_pool\forbidden_combinations.json" Link="data\forbidden_combinations.json" CopyToOutputDirectory="PreserveNewest" />
  </ItemGroup>

</Project>
